bind_address = "127.0.0.1"
port = 8000

# How many slots to show on each page
columns = 4
rows = 8

ssl_enabled = false
ssl_keyfile = 'dev.key'
ssl_certfile = 'dev.cert'

# Only enable if using ssl with a trusted certificate
auth_enabled = false
username = 'admin'
password = 'password'

# The section below defines the buttons to display on each page
#
# All buttons must have a text field
#
# If the button contains the keyboard attribute set to true,
# a virtual keyboard will be shown in this slot. Be sure to
# set column_span and row_span to ensure to keyboard has
# enough space to be displayed.
#
# If the button has an href field it will act a link. This
# allows you to navigate between pages.
#
# If the button has a command field it will be executed
# when the button is clicked. See available commands below.

# Available Commands:
#
# launch path_to_executable arg1 arg2...
# Runs a program with optional arguments
#
# hotkey keys
# Presses a single key or a hotkey
# To send special keys, surround them with {}
# ["hotkey", "a"] presses the a key
# ["hotkey", "{enter}"] presses the enter key
# ["hotkey", "{ctrl}c"] presses CTRL + C

[[pages.Main]]
text = "NextPVR"
href = "/page/NextPVR"

[[pages.Main]]
text = "Shutdown"
command = ["launch", "shutdown.exe",  "/s"]
column = 4
row = 1

[[pages.Main]]
keyboard = true
column = 1
row = 6
column_span = 4
row_span = 3

[[pages.NextPVR]]
text = "Back"
href = "/"

[[pages.NextPVR]]
text = "Launch NextPVR"
command = ["launch", "C:\\Program Files\\NextPVR\\client\\NextPVR.exe"]

[[pages.NextPVR]]
text = "Recordings"
command = ["hotkey", "{f8}"]

[[pages.NextPVR]]
text = "Esc"
command = ["hotkey", "{esc}"]
column = 2
row = 6

[[pages.NextPVR]]
text = "Up"
command = ["hotkey", "{up}"]
column = 3
row = 6

[[pages.NextPVR]]
text = "Subtitles"
command = ["hotkey", "x"]
column = 4
row = 6

[[pages.NextPVR]]
text = "Left"
command = ["hotkey", "{left}"]
column = 2
row = 7

[[pages.NextPVR]]
text = "Enter"
command = ["hotkey", "{enter}"]
column = 3
row = 7

[[pages.NextPVR]]
text = "Right"
command = ["hotkey", "{right}"]
column = 4
row = 7

[[pages.NextPVR]]
text = "Guide"
command = ["hotkey", "{f1}"]
column = 2
row = 8

[[pages.NextPVR]]
text = "Down"
command = ["hotkey", "{down}"]
column = 3
row = 8

[[pages.NextPVR]]
text = "Play/Pause"
command = ["hotkey", "{playpause}"]
column = 4
row = 8